name: docker-deploy

on:
  workflow_call:
    secrets:
      WATCHTOWER_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Watchtower Update
        run: |
          curl -X POST \
            -H "Authorization: Bearer hNHLtEUwk44Berr2oZhboie4DGqZMx2IAt3xgZJ3" \
            https://watchtower.joinup.co.in/v1/update

      - name: Verify Deployment
        run: |
          echo "Watchtower update triggered successfully at $(date)"
          echo "Application should be updated shortly"
